version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: brighte_eats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      start_period: 5s

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    user: "node"
    command: ["/bin/sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run seed && npm start"]
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/brighte_eats"

volumes:
  postgres_data:

